name: 'Publish application'
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET 8
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '8.0.x'

        # Run tests
        - name: Test
          run: dotnet test

        # Generate the website
        - name: Publish
          run: dotnet publish BlazorGithub/BlazorGithub.csproj -c:Release -p:GHPages=true -o dist/Web --nologo

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v3.9.3
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: dist/Web/wwwroot
            allow_empty_commit: false
            force_orphan: true
